name: Simple Pipeline

on:
  push:
    branches:
      - tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  pipeline:
    name: Pipeline
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
    
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - run: pnpm install --frozen-lockfile
      - run: pnpx playwright install chromium
      - run: pnpm run ci
        env:
          MODE: test
          VITE_API_BASE_URL: http://localhost:3000
  