name: Simple Pipeline

on:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  pipeline:
    name: Pipeline
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      MODE: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
    
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Build
        run: pnpm build
      
      - name: Run Lint
        run: pnpm lint

      # - name: Unit Tests
      #   working-directory: apps/web
      #   env: 
      #     VITE_API_BASE_URL: ${{ env.VITE_API_BASE_URL }}
      #   run: pnpm test

      - name: Install Playwright Browsers
        working-directory: apps/web
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright tests
        working-directory: apps/web
        env: 
          VITE_API_BASE_URL: ${{ env.VITE_API_BASE_URL }}
        run: pnpm exec playwright test
  